version: '3'
services:
  order-management-db-container:
    image: 'postgres:11'
    container_name: order-management
    environment:
      - POSTGRES_DB=ordermanagementdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - order-management

volumes:
  db_data:

networks:
  order-management:
    driver: bridge
